create or replace TRIGGER UPDATE_JOB_APPLICATION
BEFORE UPDATE OF AVAILABILITY_STATUS ON JOB_POSTING
REFERENCING OLD AS OLD NEW AS NEW
FOR EACH ROW
DECLARE
    status JOB_POSTING.AVAILABILITY_STATUS%TYPE;
BEGIN

    status:=:NEW.AVAILABILITY_STATUS;
    IF (status='N') THEN
        UPDATE JOB_APPLICATIONS
        SET STATUS='JOB UNAVAILABLE'
        WHERE JOB_POSTING_JOB_ID=:NEW.JOB_ID;
    END IF;
    IF (status='R') THEN
        UPDATE JOB_APPLICATIONS
        SET STATUS='UNDER REVIEW'
        WHERE JOB_POSTING_JOB_ID=:NEW.JOB_ID;
    END IF;
END;